format = """
[  ](bg:#a3aed2 fg:#090c0c)\
[ ](bg:#769ff0 fg:#a3aed2)\
$directory\
[ ](fg:#769ff0 bg:#394260)\
$time\
[ ](fg:#394260 bg:#1d2230)\
$battery\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[time]
disabled = false
time_format = "%R"                                     # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](fg:#769ff0 bg:#394260)]($style)'

[battery]
full_symbol = "󰂄 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂌 "
format = "[[$symbol $percentage ](fg:#a0a9cb bg:#1d2230)]($style)"

[[battery.display]]
threshold = 100
style = 'white bg:#1d2230'
