#main settings
format = """\
[   ](bg:#A32CC4)\
[](fg:#A32CC4 bg:#23395D)\
[ powershell ](bg:#23395D)\
[](fg:#23395D bg:#008B8B)\
[ mingfei ](bg:#008B8B)\
[](fg:#008B8B bg:#570816)\
$time\
[](fg:#570816 bg:#8B8000)\
$cmd_duration\
[](fg:#8B8000 bg:#20C073)\
$battery\
[](fg:#20C073)
$directory  """
add_newline = true

# directory settings
[directory]
format = "[ $path](blue)"
truncation_length = 3
truncation_symbol = "…/"
home_symbol = ""

# Battery settings
[battery]
format = "[ $symbol$percentage ]($style)"
full_symbol = " "
charging_symbol = " "
discharging_symbol = " "
unknown_symbol = " "
empty_symbol = " "

[[battery.display]]
threshold = 100
discharging_symbol = " "
style = "bg:#20C073"

[[battery.display]]
threshold = 75
style = "bold yellow"
discharging_symbol = " "

[[battery.display]]
threshold = 50
style = "bold yellow"
discharging_symbol = " "

[[battery.display]]
threshold = 25
style = "bold red"
discharging_symbol = " "

# time settings
[time]
disabled = false
time_format = "%H:%M"
format = "[  $time ](fg:bold white bg:#570816)"

#command settings
[cmd_duration]
min_time = 0
format = "[ $duration ](fg:bold white bg:#8B8000)"