#----------------------------------------------------------
#   ____            _          _    _ _
#  | __ )  __ _ ___| |__      / \  | (_) __ _ ___  ___  ___
#  |  _ \ / _` / __| '_ \    / _ \ | | |/ _` / __|/ _ \/ __|
#  | |_) | (_| \__ \ | | |  / ___ \| | | (_| \__ \  __/\__ \
#  |____/ \__,_|___/_| |_| /_/   \_\_|_|\__,_|___/\___||___/
#
#----------------------------------------------------------
# This file contains some custom bash aliases
# along with some personal bash config to avoid
# mixing with .bashrc file in the home directory
#
# p/s: this is a known working version and only
# change ths when all changes are tested properly
#----------------------------------------------------------

#----------------------------------------------------------
# alias for apt operations
alias in='sudo apt install'
alias up='sudo apt update && sudo apt upgrade -y'
alias autorm='sudo apt autoremove && sudo apt autoclean && sudo apt clean'
alias aptrm='sudo apt remove'
#----------------------------------------------------------

#----------------------------------------------------------
# some terminal shortcut
# allow the creation of subdirectories
alias mkdir='mkdir -pv'

# allow interactive mode
alias mv='mv -i'
alias cp='cp -i'
alias rm='rm -i'

# alias for git auto detect changes and commit plus push
alias submit='git add . && git commit -a && git push'
#----------------------------------------------------------

#----------------------------------------------------------
# alias for apps
alias v='nvim'
alias duf='duf -hide special'
alias rng='ranger'
alias cm='cmatrix'
alias nf='neofetch'
alias ff='figlet -f slant.flf Debian | lolcat && fastfetch -l none'
alias scrwb='scrcpy --window-borderless'
alias gdrive='thunar && rclone mount google-drive: ~/Documents/gdrive/'
alias zz='zellij --layout compact'
alias lg='lazygit'
#----------------------------------------------------------

#----------------------------------------------------------
# alias for system information call
alias clock='tty-clock -c -B'
alias off='poweroff'
alias cl='clear'
#----------------------------------------------------------

#----------------------------------------------------------
# run neofetch on startup
# neofetch
figlet -f slant.flf Debian | lolcat && fastfetch -l none

# initiate starship prompt when launching terminal
eval "$(starship init bash)"

#set input mode to be vim modal keybinding
set -o vi
export EDITOR=nvim
#----------------------------------------------------------

#----------------------------------------------------------
# EOF
#----------------------------------------------------------
export GOPATH=$HOME/go
